site_name: 'python-app-template'
site_description: 'Main documentation for the python-app-template'
repo_url: https://github.com/raftriani/python-app-template
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'